# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:

# HTML Title
title: "Juan and Bri"

# Avatar image path
avatar: "./images/profile.jpeg"

# Name section text
name: "Juan and Bri"

# Tagline section text
tagline: 'Hey, you found us!Juan does tech things and Bri does art things.'

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-mastodon"
      url: "https://infosec.exchange/@pinche_juan"
      title: "Juan's Mastodon"
      alt: "Juan's Mastodon"
      target: "_blank"
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/cheesiebri/"
      title: "Bri's Instagram"
      alt: "Bri's Instagram"
      target: "_blank"

# Footer text
footer: >
    We might take some time to get back to you.

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
#copyright: >
#  © 2024  <a href="https://zhgchg.li" target="_blank">ZhgChgLi</a>. Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
